# Generated by Django 4.0.5 on 2022-06-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_estudiantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profesion', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
